# Generated by Django 6.0.1 on 2026-01-12 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
