# Generated by Django 6.0.1 on 2026-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
